version: '3.8'
services:
  db:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/src/main/resources/db
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring

networks:
    monitoring:
      driver: bridge